# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django_lti_login.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lti_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticlient',
            name='key',
            field=models.CharField(default=django_lti_login.models.create_new_key, help_text='LTI client service key', max_length=128, primary_key=True, serialize=False, validators=[django_lti_login.models.key_validator]),
        ),
        migrations.AlterField(
            model_name='lticlient',
            name='secret',
            field=models.CharField(default=django_lti_login.models.create_new_secret, help_text='LTI client service secret', max_length=128, validators=[django_lti_login.models.secret_validator]),
        ),
    ]
